* Make a game in a year
I want to make a game fully polished within a year. The only way to do that is to make the gameplay simple enough I can spend my time on UI and polish.

Readying the history of games gave me an idea I could steal- I mean copy: Fox and Geese.

You control the Fox on a map with several Geese.
You all move at the same time, like a chessboard.
If 3 or more Geese touch you at the same time, you lose.
If you touch a Goose, you kill it.

The mission is to kill all the Geese before they kill you.

* Style
A cops and robbers motif? The Fox Thief eludes the Goose Robbers?
A pulp superhero motif? The Foxman escapes the Goose Mob?

* Kivy Screen control
Game Controller is always running.

** Title Screen
Title Screen Controller shows the title screen along with a "Start Game" button.

** Mission Controller
Game Screen has a map. It has a Title Screen button.
After you win or lose, only the Title Screen button is available.
During a map, you have up down left right buttons.
* Timetable
1 month: Proof of Concept. [2016-11-05 Sat]
3 months: Builds on multiple platforms (Alpha?)
6 months: Prototype (Beta?)
1 year: Game complete ready to ship.
* Development TODOs
** Mission Controller
Add unit tests to move an Entity 1 space.
- Test against a wall

*** MissionView

Needs to know the mission model so it knows the size of the map.
Needs to know where ot get resources to build sprites.
Needs to track the sprites.

Needs to be aware of updates.

Has to know when to say
MISSION START
MISSION COMPLETE
FAILURE

Has to know when to pass player input to the mission controller
Has to know when to ask the other entities to move
Has to animate the sprites moving around
Has to animate the sprites dying

Build a variable that shows what the view is waiting for.
Mission Controller to be initialized
Mission Start to finish displaying
Player Input
Finish Animating This Round's Results
Show Mission Complete message
